### ISSUE TITLE
Implementation of non-linear power spectrum

### ISSUE THREAD

**Issue by EiffL** [DifferentiableUniverseInitiative/jax_cosmo#10]
We only have an EH linear power spectrum currently, and should implement some non-linear corrections. 
I have placed in `jax_cosmo/nonlinear.py` some code inherited from comicpy for smith et al. 2003 non-linear corrections. But I haven't turned it into proper working code yet.

We should:
  - [ ] Implement a standard mechanism for non-linear corrections in `jax_cosmo/power.py`
  - [ ] Add specific utilities for a given correction in `jax_cosmo/nonlinear.py`

**Comment by santiagocasas** [comment]
For the mildly non-linear matter Pk, one can apply some of the integrals of perturbation theory / EFToLSS, but rewriting them into JAX. Recent codes, like FASTPT or pyBird do this very efficiently and they don't even use jit or any parallelization. It's mostly FFTLog integrals.
For deeply non-linear Pk, the best would be to have a quick emulator and write those coefficients also within JAX.

**Comment by EiffL** [comment]
I'm pretty sure I can get halofit in easily. But I've been looking at FAST-PT..... it's pure python code as far as I can tell....
