### ISSUE TITLE
[bug?] `jc.background.H` uses H0 = 100 instead of H0=h*100.

### ISSUE THREAD

**Issue by arthurmloureiro** [DifferentiableUniverseInitiative/jax_cosmo#101]
In the calculation of the Hubble Parameter, the function makes use of `const.H0` (set to 100 [here](https://github.com/DifferentiableUniverseInitiative/jax_cosmo/blob/52ca0093968467269c8c73eed1fa00433eadbebc/jax_cosmo/constants.py#L21)) instead of using the cosmological parameter `H0` (`cosmo.h * 100`).

The following lines return different values:
```python
H_at_z = jc.background.H(cosmo, jc.utils.z2a(0.38))
H_at_z2 = np.sqrt(jc.background.Esqr(cosmo, jc.utils.z2a(0.38))*((cosmo.h*100)**2))
```
First line returns (`H_at_z`): `119.22084`
Second line returns (`H_at_z2`): `83.45459`

Running the same over `classy` returns: `83.46082`.

I can send a MR to fix it, but it should be pretty straight-forward :)

**Comment by andrevitorelli** [comment]
This will just make any output come in terms of h^n, as it is done in most literature - so I wouldn't see a reason to change. Maybe the documentation should be more specific on that somewhere.

**Comment by arthurmloureiro** [comment]
Ok, that makes sense! I missed the /h in the documentation and then checking across class the different values made me think there was an issue hehe
