### ISSUE TITLE
Intro notebook fails on colab

### ISSUE THREAD

**Issue by dkirkby** [DifferentiableUniverseInitiative/jax_cosmo#59]
I am running `docs/notebooks/jax-cosmo-intro` on colab with a CPU-only runtime and the following line:
```
F = - hessian_loglik(params)
```
gives a mysterious error:
```
TypeError: Integers cannot be raised to negative powers, got integer_pow(ShapedArray(int32[513,1]), -2)
```
Any idea why this is being traced with an integer array here?

**Comment by dkirkby** [comment]
I just checked that I get the same error with a GPU runtime.

**Comment by EiffL** [comment]
Yes, thank you! I spent some time to track down the issue, apparently it was something broken in jax, checkout this issue:
https://github.com/google/jax/issues/3861

It should work again with the latest version of JAX.... this happens sometime...  but the JAX devs are super responsive and usually very quickly find fixes

**Comment by dkirkby** [comment]
Nice sleuthing (and great to see the jax devs so responsive) - thanks!

**Comment by EiffL** [comment]
I've just pushed updated the colab notebook, by adding a jax update at the beginning and printing out versions of both jax and jax-cosmo. This should help next time around ^^'

@all-contributors please add @dkirkby for bug
