### ISSUE TITLE
Disagreement in the angular power spectrum between jax-cosmo and CCL

### ISSUE THREAD

**Issue by dlanzieri** [DifferentiableUniverseInitiative/jax_cosmo#69]
Hi, I was trying to compare the results of my project with the Angular Power Spectrum obtained using Jax-cosmo and CCL, but I've noticed that the two libraries seem to disagree in particular situation. For instance, I've implemented a simple working example as follows:
```ruby
  cosmo_ccl = ccl.Cosmology(
  Omega_c=0.2589, Omega_b=0.0486, 
  h=0.6774, sigma8 = 0.8159, n_s=0.9667, Neff=0,
  transfer_function='eisenstein_hu', matter_power_spectrum='halofit')
  cosmo_jc = jc.Planck15()
  z_source=1.
  l= np.logspace(2.2,4, 250)
  z = linspace(0,2,2048)
  pz = zeros_like(z)
  pz[argmin(abs(z_source - z))] = 1. 
  nzs_s=jc.redshift.kde_nz(z, pz, bw=0.01)
  tracer=ccl.WeakLensingTracer(cosmo_ccl, (z, nzs_s(z)), use_A_ia=False)
  cl_ccl = ccl.angular_cl(cosmo_ccl, tracer, tracer, l) 
  probes = [ jc.probes.WeakLensing([nzs_s], sigma_e=0.26) ]
  cls = jc.angular_cl.angular_cl(cosmo_jc, l, probes)
```
and I get the following result:

![jaxcshalo](https://user-images.githubusercontent.com/72620117/116725230-f2badb80-a9e1-11eb-9c0c-5098d8f68c6a.png)

We suppose that problem is due to the fact that the redshift distribution is a single source plane. @EiffL suggested to add a new type of redshift distribution in this [file](https://github.com/DifferentiableUniverseInitiative/jax_cosmo/blob/master/jax_cosmo/redshift.py) defined by a single non-null redshift.

**Comment by EiffL** [comment]
ok so here is what I think the single source redshift distribution should look like:

```python
class single_plane(redshift_distribution):
    """Defines a single plane redshift distribution with these arguments
    Parameters:
    -----------
    z0:
    """
    def pz_fn(self, z):
        z0 = self.params
        return np.where(z == z0, 1., 0)
```

**Comment by dlanzieri** [comment]
Hi @EiffL!  I modified the  [weak_lensing_kernel](https://github.com/DifferentiableUniverseInitiative/jax_cosmo/blob/6124096854119459bb27bda718d4d440d87f306b/jax_cosmo/probes.py#L19) function to work with a single non-null redshift. I also added a [notebook](https://github.com/DifferentiableUniverseInitiative/jax_cosmo/blob/6124096854119459bb27bda718d4d440d87f306b/docs/notebooks/single_plane.ipynb) where I tried to compute the angular power spectrum for different redshift distributions. 
Could you have a look at it?

**Comment by EiffL** [comment]
Fantastic, thanks @dlanzieri I will take a look! Would you mind opening a draft Pull Request?

**Comment by EiffL** [comment]
It looks very good!

We can just add a test here in https://github.com/DifferentiableUniverseInitiative/jax_cosmo/blob/single_source/tests/test_angular_cl.py 
that should check we get the right cl for a single source lensplane.

We'll also probably want to add a warning if someone tries to use a single source plane for clustering that it's probably not going to work. But I can't really imagine why someone would need to compute that....
